import "./globals.css";
import type { Metadata } from "next";
import { Lemon } from "next/font/google";
import { AuthProvider } from "../app/context/authContext";

const lemon = Lemon({ subsets: ["latin"], weight: "400", display: "swap" });

export const metadata: Metadata = {
  title: "GYM APP",
  description: "Generated by NextJs",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={lemon.className}>{children}</body>
      </html>
    </AuthProvider>
  );
}
